name: Build and Upload Windows Executable

on:
  release:
    types: [ published ]

jobs:
  build-windows-exe:
    runs-on: windows-2022
    env:
      PYTHON_VERSION: '3.12'
      EXE_NAME: peakls.exe
      ENTRY_SCRIPT: main.py

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: ${{ env.PYTHON_VERSION }}

      - name: Create virtual environment
        run: python -m venv venv

      - name: Activate venv and install dependencies
        run: |
          .\venv\Scripts\activate
          python -m pip install --upgrade pip
          pip install pyinstaller
          pip install -r requirements.txt

      - name: Build executable with PyInstaller
        run: |
          .\venv\Scripts\activate
          pyinstaller --onefile --name $env:EXE_NAME $env:ENTRY_SCRIPT

      - name: Export LATEST_TAG
          run: |
            echo "LATEST_TAG=$(curl -qsSL \
              -H "Accept: application/vnd.github+json" \
              -H "Authorization: Bearer ${{ secrets.GITHUB_TOKEN }}" \
              -H "X-GitHub-Api-Version: 2022-11-28" \
              "${{ github.api_url }}/repos/${{ github.repository }}/releases/latest" \
            | jq -r .tag_name)" >> $GITHUB_ENV
      - name: Upload Release Artifact
          env:
            GH_TOKEN: ${{ secrets.ACCESS_TOKEN }}
          run:
            gh release upload ${{ env.LATEST_TAG }} dist\${{ env.EXE_NAME }}